---
services:
  elasticsearch:
    container_name: "elasticsearch"
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.13.4"
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "xpack.security.http.ssl.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - "elasticsearch_data:/usr/share/elasticsearch/data"
    healthcheck:
      test:
        - "CMD-SHELL"
        - "curl -s -f 'http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=1s' || exit 1"
      interval: "15s"
      timeout: "10s"
      retries: 10
      start_period: "40s"

  spicedb:
    image: "authzed/spicedb:latest"
    command: 'serve --grpc-preshared-key "devtoken"'
    ports:
      - "50051:50051"
    environment:
      SPICEDB_DATASTORE_ENGINE: "memory"

volumes:
  elasticsearch_data:
