{
 "title": "SpiceDB",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "interval",
    "query": "15s,30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "permission_system",
    "query": {
     "query": "label_values(grpc_server_handling_seconds_count{grpc_service=~\".*Health\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "API Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "API RPS",
   "type": "timeseries",
   "description": "RPS as perceived by the server",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(grpc_code) (rate(grpc_server_handled_total{grpc_service=~\".*PermissionsService|.*SchemaService|authzed.api.v1.ExperimentalService\"}[$__rate_interval]))",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  {
   "title": "API Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(grpc_method) (increase(grpc_server_handling_seconds_count{grpc_service=~\".*PermissionsService|.*SchemaService|authzed.api.v1.ExperimentalService\"}[$__rate_interval]))",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "p95 Check Latency over last 24h",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"CheckPermission\"}[24h])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "API 4XX Errors (Server)",
   "type": "timeseries",
   "description": "4XX errors returned by API as perceived by Server",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(grpc_code) (increase(grpc_server_handled_total{grpc_code!=\"OK\", grpc_code!=\"Canceled\", grpc_code!=\"DeadlineExceeded\", grpc_code!=\"Unavailable\", grpc_code!=\"Internal\", grpc_code!=\"Unknown\", grpc_service=~\".*PermissionsService|.*SchemaService|authzed.api.v1.ExperimentalService\"}[$__rate_interval]))",
     "legendFormat": "{{grpc_method}} ({{grpc_code}})"
    }
   ]
  },
  {
   "title": "API 5XX Errors (Server)",
   "type": "timeseries",
   "description": "5XX errors returned by API as perceived by Server",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(grpc_method, grpc_code) (increase(grpc_server_handled_total{grpc_code!=\"OK\", grpc_code!=\"AlreadyExists\", grpc_code!=\"Canceled\", grpc_code!=\"InvalidArgument\", grpc_code!=\"NotFound\", grpc_code!=\"PermissionDenied\", grpc_code!=\"FailedPrecondition\", grpc_service=~\".*PermissionsService|.*SchemaService|.*ExperimentalService\"}[$__rate_interval]))",
     "legendFormat": "{{grpc_method}} ({{grpc_code}})"
    }
   ]
  },
  {
   "title": "Subproblem Cache Hit Ratio",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(spicedb_services_dispatches_sum{cached=\"true\"}[$__rate_interval])) / sum(rate(spicedb_services_dispatches_sum[$__rate_interval]))",
     "legendFormat": "cache hit rate"
    }
   ]
  },
  {
   "title": "Total vs Singleflighted Dispatches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(spicedb_dispatch_single_flight_total{shared=\"true\"}[$__rate_interval])) / sum(increase(spicedb_dispatch_single_flight_total[$__rate_interval]))",
     "legendFormat": "singleflight/{{shared}}"
    }
   ]
  },
  {
   "title": "API RPS By Requested Consistency",
   "type": "timeseries",
   "description": "RPS as perceived by the server",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(method, source) (rate(spicedb_middleware_consistency_assigned_total[$__rate_interval]))",
     "legendFormat": "{{method}}/{{source}}"
    }
   ]
  },
  {
   "title": "API RPS",
   "type": "piechart",
   "description": "RPS as perceived by the server",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(grpc_method) (rate(grpc_server_handled_total{grpc_service=~\".*PermissionsService|.*SchemaService|authzed.api.v1.ExperimentalService\"}[$__rate_interval]))",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  {
   "title": "API RPS Dispatch Distribution per Pod",
   "type": "piechart",
   "description": "RPS as perceived by the server",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(grpc_server_handled_total{grpc_service=~\"dispatch.v1.DispatchService\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "API RPS Dispatch Distribution per Pod",
   "type": "timeseries",
   "description": "RPS as perceived by the server",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(grpc_server_handled_total{grpc_service=~\"dispatch.v1.DispatchService\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}-{{grpc_method}}"
    }
   ]
  },
  {
   "title": "API RPS Distribution per Pod",
   "type": "timeseries",
   "description": "RPS as perceived by the server",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(grpc_server_handled_total{grpc_service=~\".*PermissionsService|.*SchemaService|authzed.api.v1.ExperimentalService\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Prober",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thumper Errors By Method",
     "type": "timeseries",
     "description": "Error codes by method as perceived by the API probe, Thumper",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 146 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(grpc_method, grpc_code) (increase(grpc_client_handled_total{container=\"thumper\", grpc_code=~\"Unknown|Aborted|Internal|Unavailable|DataLoss|DeadlineExceeded\"}[$__rate_interval]))",
       "legendFormat": "{{grpc_method}} ({{grpc_code}})"
      }
     ]
    },
    {
     "title": "API Availability",
     "type": "timeseries",
     "description": "Perceived by Thumper",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 146 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(increase(grpc_client_handled_total{grpc_code=~\"OK|Aborted|Canceled\", grpc_service=~\".*PermissionsService|.*SchemaService|.*ExperimentalService\"}[$__rate_interval])) / sum(increase(grpc_client_handled_total{grpc_service=~\".*PermissionsService|.*SchemaService|.*ExperimentalService\"}[$__rate_interval]))",
       "legendFormat": "API availability"
      }
     ]
    },
    {
     "title": "API Availability Over last 10m",
     "type": "gauge",
     "description": "Perceived by Thumper",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 146 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(grpc_client_handled_total{grpc_code=~\"OK|Aborted|Canceled\", grpc_service=~\".*PermissionsService|.*SchemaService|.*ExperimentalService\"}[10m])) / sum(increase(grpc_client_handled_total{grpc_service=~\".*PermissionsService|.*SchemaService|.*ExperimentalService\"}[10m]))",
       "legendFormat": "API availability"
      }
     ]
    },
    {
     "title": "Thumper Errors By Code",
     "type": "timeseries",
     "description": "Distribution of gRPC error codes as perceived by the API probe, Thumper",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 154 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(grpc_code) (increase(grpc_client_handled_total{container=\"thumper\"}[$__rate_interval]))",
       "legendFormat": "{{tenant}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Per Service RPS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "PersmissionService RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(grpc_code) (rate(grpc_server_handled_total{grpc_service=\"authzed.api.v1.PermissionsService\"}[$__rate_interval]))",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    },
    {
     "title": "ExperimentalService RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(grpc_code) (rate(grpc_server_handled_total{grpc_service=\"authzed.api.v1.ExperimentalService\"}[$__rate_interval]))",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    },
    {
     "title": "DispatchService RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(grpc_code) (rate(grpc_server_handled_total{grpc_service=\"dispatch.v1.DispatchService\"}[$__rate_interval]))",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    },
    {
     "title": "SchemaService RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(grpc_code) (rate(grpc_server_handled_total{grpc_service=\"authzed.api.v1.SchemaService\"}[$__rate_interval]))",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CheckPermission",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "p95 over last 10m",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"CheckPermission\"}[10m])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "CheckPermission Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"CheckPermission\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"CheckPermission\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "CheckRelationships Success Rate over last 10m",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(delta(grpc_server_handled_total{grpc_method=\"CheckPermission\", grpc_code=\"OK\"}[10m])) / sum(delta(grpc_server_handled_total{grpc_method=\"CheckPermission\"}[10m]))",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  {
   "title": "CheckPermission P95 week-over-week",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"CheckPermission\"}[$__rate_interval])))",
     "legendFormat": "p95 today"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"CheckPermission\"}[$__rate_interval] offset 1w)))",
     "legendFormat": "p95 last week"
    }
   ]
  },
  {
   "title": "CheckPermission RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(grpc_code) (rate(grpc_server_handled_total{grpc_method=\"CheckPermission\"}[$__rate_interval]))",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  {
   "title": "BulkCheckPermission",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "p95 over last 10m",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 359 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"BulkCheckPermission\"}[10m])))",
       "legendFormat": "p95"
      }
     ]
    },
    {
     "title": "BulkCheckPermission Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 359 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"BulkCheckPermission\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"BulkCheckPermission\"}[$__rate_interval])))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "BulkCheckPermission RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 359 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(grpc_code) (rate(grpc_server_handled_total{grpc_method=\"BulkCheckPermission\"}[$__rate_interval]))",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "LookupResources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "LookupResources Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 296 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"LookupResources\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"LookupResources\"}[$__rate_interval])))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "LookupResources RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 296 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(grpc_code) (rate(grpc_server_handled_total{grpc_method=\"LookupResources\"}[$__rate_interval]))",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "LookupSubjects",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "LookupSubjects Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 297 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"LookupSubjects\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"LookupSubjects\"}[$__rate_interval])))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "LookupSubjects RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 297 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(grpc_code) (rate(grpc_server_handled_total{grpc_method=\"LookupSubjects\"}[$__rate_interval]))",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Expand",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "ExpandPermissionTree Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 298 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"ExpandPermissionTree\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"ExpandPermissionTree\"}[$__rate_interval])))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "ExpandPermissionTree RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 298 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(grpc_code) (rate(grpc_server_handled_total{grpc_method=\"ExpandPermissionTree\"}[$__rate_interval]))",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ReadRelationships",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "ReadRelationships Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 243 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"ReadRelationships\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"ReadRelationships\"}[$__rate_interval])))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "ReadRelationships RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 243 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(grpc_code) (rate(grpc_server_handled_total{grpc_method=\"ReadRelationships\"}[$__rate_interval]))",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "WriteRelationships",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "WriteRelationships Latency Over Last 10m",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(grpc_server_handling_seconds_bucket{grpc_method=\"WriteRelationships\"}[10m])) by (le))",
       "legendFormat": "p95"
      }
     ]
    },
    {
     "title": "WriteRelationships Success Rate over last 10m",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum (delta(grpc_server_handled_total{grpc_method=\"WriteRelationships\", grpc_code=\"OK\"}[10m])) / sum (delta(grpc_server_handled_total{grpc_method=\"WriteRelationships\"}[10m]))",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    },
    {
     "title": "WriteRelationships Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(grpc_code) (increase(grpc_server_handled_total{grpc_method=\"WriteRelationships\"}[$__rate_interval]))",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    },
    {
     "title": "WriteRelationships Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"WriteRelationships\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"WriteRelationships\"}[$__rate_interval])))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "WriteRelationships RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(grpc_code) (rate(grpc_server_handled_total{grpc_method=\"WriteRelationships\"}[$__rate_interval]))",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DeleteRelationships",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "DeleteRelationships Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 245 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"DeleteRelationships\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(grpc_server_handling_seconds_bucket{grpc_method=\"DeleteRelationships\"}[$__rate_interval])))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "DeleteRelationships RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 245 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(grpc_code) (rate(grpc_server_handled_total{grpc_method=\"DeleteRelationships\"}[$__rate_interval]))",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    },
    {
     "title": "DeleteRelationships RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 245 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(grpc_code) (increase(grpc_server_handled_total{grpc_method=\"DeleteRelationships\"}[$__rate_interval]))",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dispatching",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Dispatched Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(spicedb_dispatch_check_total[$__rate_interval]))",
     "legendFormat": "check"
    },
    {
     "expr": "sum(rate(spicedb_dispatch_client_lookup_total[$__rate_interval]))",
     "legendFormat": "lookup resources"
    },
    {
     "expr": "sum(rate(spicedb_dispatch_reachable_resources_total[$__rate_interval]))",
     "legendFormat": "reachable resources"
    },
    {
     "expr": "sum(rate(spicedb_dispatch_client_lookup_subjects_total[$__rate_interval]))",
     "legendFormat": "lookup subjects"
    }
   ]
  },
  {
   "title": "Subproblem Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(spicedb_services_dispatches_sum{cached=\"true\"}[$__rate_interval])) / sum(rate(spicedb_services_dispatches_sum[$__rate_interval]))",
     "legendFormat": "cache hit rate"
    }
   ]
  },
  {
   "title": "Dispatch Per Request Ratio",
   "type": "timeseries",
   "description": "RPS as perceived by the server",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_service=\"dispatch.v1.DispatchService\", grpc_method=\"DispatchCheck\"}[$__rate_interval])) / sum(rate(grpc_server_handled_total{grpc_service=~\".*PermissionsService\", grpc_method=\"CheckPermission\"}[$__rate_interval]))",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  {
   "title": "Cache Bytes Added / Evicted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(cache) (rate(spicedb_cache_cost_added_bytes[$__rate_interval]))",
     "legendFormat": "{{cache}} added"
    },
    {
     "expr": "-sum by(cache) (rate(spicedb_cache_cost_evicted_bytes[$__rate_interval]))",
     "legendFormat": "{{cache}} evicted"
    }
   ]
  },
  {
   "title": "Dispatch Caching Ratio (client)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(spicedb_dispatch_client_check_from_cache_total[$__rate_interval])) / sum(rate(spicedb_dispatch_client_check_total[$__rate_interval]))",
     "legendFormat": "check"
    },
    {
     "expr": "sum(rate(spicedb_dispatch_client_lookup_from_cache_total[$__rate_interval])) / sum(rate(spicedb_dispatch_client_lookup_total[$__rate_interval]))",
     "legendFormat": "lookup resources"
    },
    {
     "expr": "sum(rate(spicedb_dispatch_client_reachable_resources_from_cache_total[$__rate_interval])) / sum(rate(spicedb_dispatch_client_reachable_resources_total[$__rate_interval]))",
     "legendFormat": "reachable resources"
    },
    {
     "expr": "sum(rate(spicedb_dispatch_client_lookup_subjects_from_cache_total[$__rate_interval])) / sum(rate(spicedb_dispatch_client_lookup_subjects_total[$__rate_interval]))",
     "legendFormat": "lookup subjects"
    }
   ]
  },
  {
   "title": "Dispatch Caching Ratio (server)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(spicedb_dispatch_check_from_cache_total[$__rate_interval])) / sum(rate(spicedb_dispatch_check_total[$__rate_interval]))",
     "legendFormat": "check"
    },
    {
     "expr": "sum(rate(spicedb_dispatch_lookup_from_cache_total[$__rate_interval])) / sum(rate(spicedb_dispatch_lookup_total[$__rate_interval]))",
     "legendFormat": "lookup resources"
    },
    {
     "expr": "sum(rate(spicedb_dispatch_reachable_resources_from_cache_total[$__rate_interval])) / sum(rate(spicedb_dispatch_reachable_resources_total[$__rate_interval]))",
     "legendFormat": "reachable resources"
    },
    {
     "expr": "sum(rate(spicedb_dispatch_lookup_subjects_from_cache_total[$__rate_interval])) / sum(rate(spicedb_dispatch_lookup_subjects_total[$__rate_interval]))",
     "legendFormat": "lookup subjects"
    }
   ]
  },
  {
   "title": "Cache Bytes differential By pod",
   "type": "timeseries",
   "description": "shows the rate of the difference between added and evicted. Negative values means pod is evicting more than adding and suggests memory pressure",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(spicedb_cache_cost_added_bytes[$__rate_interval])) - sum by(pod) (rate(spicedb_cache_cost_evicted_bytes[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Bytes Accumulated By Pod",
   "type": "timeseries",
   "description": "shows the difference between added and evicted. Shrinking lines indicate pod is evicting more than adding and suggests memory pressure",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (spicedb_cache_cost_added_bytes) - max by(pod) (spicedb_cache_cost_evicted_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Datastore", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "p99 Tuple per Query",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(spicedb_datastore_loaded_relationships_count_bucket[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(spicedb_datastore_loaded_relationships_count_bucket[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(spicedb_datastore_loaded_relationships_count_bucket[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(spicedb_datastore_loaded_relationships_count_bucket[$__rate_interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "QueryRelationships API Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(spicedb_datastore_query_latency_bucket{operation=\"QueryRelationships\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, operation) (rate(spicedb_datastore_query_latency_bucket{operation=\"QueryRelationships\"}[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, operation) (rate(spicedb_datastore_query_latency_bucket{operation=\"QueryRelationships\"}[$__rate_interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Datastore API Latency p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(spicedb_datastore_query_latency_bucket[$__rate_interval])))\n",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Tuples Load Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(spicedb_datastore_loaded_relationships_count_sum[$__rate_interval]))",
     "legendFormat": "tuples per second"
    }
   ]
  },
  {
   "title": "DB Query Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(operation) (rate(spicedb_datastore_query_latency_count[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Datastore GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 },
   "collapsed": true,
   "panels": [
    {
     "title": "Datastore GC latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 144 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(spicedb_datastore_gc_duration_seconds_bucket[$__rate_interval])))",
       "legendFormat": "p95"
      }
     ]
    },
    {
     "title": "Datastore GC success/errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 144 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(spicedb_datastore_gc_duration_seconds_count[$__rate_interval]))",
       "legendFormat": "success"
      },
      {
       "expr": "sum by() (increase(spicedb_datastore_gc_failure_total[$__rate_interval]))",
       "legendFormat": "failures"
      }
     ]
    },
    {
     "title": "Datastore deleted count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 144 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(spicedb_datastore_gc_relationships_total[$__rate_interval]))",
       "legendFormat": "relationships deleted"
      },
      {
       "expr": "sum(increase(spicedb_datastore_gc_transactions_total[$__rate_interval]))",
       "legendFormat": "transactions deleted"
      }
     ]
    }
   ]
  },
  {
   "title": "Datastore Hedging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Request Hedging",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 400 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(spicedb_datastore_hedgeable_requests_total[$__rate_interval]))",
       "legendFormat": "hedgeable"
      },
      {
       "expr": "sum(rate(spicedb_datastore_hedged_requests_total[$__rate_interval]))",
       "legendFormat": "hedged"
      }
     ]
    },
    {
     "title": "Hedging Ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 400 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(spicedb_datastore_hedged_requests_total[$__rate_interval])) / sum(rate(spicedb_datastore_hedgeable_requests_total[$__rate_interval]))",
       "legendFormat": "hedged"
      }
     ]
    }
   ]
  },
  { "title": "Datastore Connection Pooling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "Max Currently Acquired Conns",
   "type": "timeseries",
   "description": "The number of currently acquired connections in the pool.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "max by(pool_usage) (max_over_time(pgxpool_acquired_conns{pool_usage=~\"read|write\"}[$__interval]))",
     "legendFormat": "{{pool_usage}}"
    }
   ]
  },
  {
   "title": "Successful/Cancelled Acquisitions",
   "type": "timeseries",
   "description": "The cumulative count of successful acquires from the pool",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (pool_usage) (rate(pgxpool_acquire_count{pool_usage=~\"read|write\"}[$__rate_interval]))",
     "legendFormat": "successful ({{pool_usage}})"
    },
    {
     "expr": "max by (pool_usage) (rate(pgxpool_canceled_acquire_count{pool_usage=~\"read|write\"}[$__rate_interval]))",
     "legendFormat": "cancelled ({{pool_usage}})"
    }
   ]
  },
  {
   "title": "Max Constructing Conns",
   "type": "timeseries",
   "description": "The number of conns with construction in progress in the pool",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 106 },
   "targets": [
    {
     "expr": "max by (pool_usage) (max_over_time(pgxpool_constructing_conns{pool_usage=~\"read|write\"}[$interval]))",
     "legendFormat": "{{pool_usage}}"
    }
   ]
  },
  {
   "title": "Max time spent acquiring connections",
   "type": "timeseries",
   "description": "The maximum amount of time spnt by SpiceDB waiting to acquire a connection",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "max by(pool_usage) (rate(pgxpool_acquire_duration_ns{pool_usage=~\"read|write\"}[$__rate_interval]))",
     "legendFormat": "{{pool_usage}}"
    }
   ]
  },
  {
   "title": "AVG Total / Idle / Max",
   "type": "timeseries",
   "description": "Total: The total number of resources currently in the pool\nIdle: The number of currently idle conns in the pool\nMax: The maximum size of the pool",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(pool_usage) (pgxpool_total_conns{pool_usage=~\"read|write\"})",
     "legendFormat": "total ({{pool_usage}})"
    },
    {
     "expr": "avg by (pool_usage) (pgxpool_idle_conns{pool_usage=~\"read|write\"})",
     "legendFormat": "idle ({{pool_usage}})"
    },
    {
     "expr": "avg by (pool_usage) (pgxpool_max_conns{pool_usage=~\"read|write\"})",
     "legendFormat": "max ({{pool_usage}})"
    }
   ]
  },
  {
   "title": "Acquisitions that waited",
   "type": "timeseries",
   "description": "The cumulative count of successful acquires from the pool that waited for a resource to be released or constructed because the pool was empty",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(pool_usage) (increase(pgxpool_empty_acquire{, pool_usage=~\"read|write\"}[$__rate_interval]))",
     "legendFormat": "{{pool_usage}}"
    }
   ]
  },
  {
   "title": "new connections opened",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(pool_usage) (increase(pgxpool_new_conns_count[$__rate_interval]))",
     "legendFormat": "{{pool_usage}}"
    }
   ]
  },
  {
   "title": "max lifetime destroy count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(pool_usage) (increase(pgxpool_max_lifetime_destroy_count[$__rate_interval]))",
     "legendFormat": "{{pool_usage}}"
    }
   ]
  },
  {
   "title": "max successful acquires after empty pool",
   "type": "timeseries",
   "description": "Cumulative count of successful acquires from the pool that waited for a resource to be released or constructed because the pool was empty.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(pool_usage) (increase(pgxpool_empty_acquire{pool_usage=~\"read|write\"}[$__rate_interval]))",
     "legendFormat": "{{pool_usage}}"
    }
   ]
  },
  {
   "title": "max idle destroy count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(pool_usage) (increase(pgxpool_max_idle_destroy_count{pool_usage=~\"read|write\"}[$__rate_interval]))",
     "legendFormat": "{{pool_usage}}"
    }
   ]
  },
  {
   "title": "CockroachDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 137 },
   "collapsed": true,
   "panels": [
    {
     "title": "cockroachdb client-side tx reset distribution",
     "type": "timeseries",
     "description": "cockroachdb client-side tx reset distribution",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 402 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(crdb_client_resets_bucket) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "DB Connections per CRDB node",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 402 },
     "targets": [
      {
       "expr": "sum by (node_id) (crdb_connections_per_node)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Current Connections per CRDB node",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 402 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum by (node_id) (crdb_connections_per_node)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Healthy CRDB nodes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 409 },
     "targets": [
      {
       "expr": "sum by (pod) (crdb_healthy_nodes)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CRDB retry pool vs pgx pool connections",
     "type": "timeseries",
     "description": "Difference between spicedb's tracked connections and pgx pool stats. This value should never be a sustained non-zero value.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 409 },
     "targets": [
      {
       "expr": "sum(crdb_connections_per_node{pool=\"read\"}) - sum(pgxpool_total_conns{pool_usage=\"read\"})",
       "legendFormat": "Read Pool"
      },
      {
       "expr": "sum(crdb_connections_per_node{pool=\"write\"}) - sum(pgxpool_total_conns{pool_usage=\"write\"})",
       "legendFormat": "Write Pool"
      }
     ]
    },
    {
     "title": "Time spent pruning p95 (ms)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 409 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, pool) (rate(crdb_pruning_duration_bucket[$__rate_interval])))",
       "legendFormat": "Read Pool"
      }
     ]
    }
   ]
  },
  {
   "title": "Spanner",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 138 },
   "collapsed": true,
   "panels": [
    {
     "title": "spanner roundtrip latency p99",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 171 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, operation, grpc_client_method) (rate(spicedb_grpc_io_client_roundtrip_latency_bucket[$__rate_interval])))",
       "legendFormat": "{{grpc_client_method}}"
      }
     ]
    },
    {
     "title": "GFE Latency p99",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 171 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, grpc_client_method) (rate(spicedb_cloud_google_com_go_spanner_gfe_latency_bucket[$__rate_interval])))",
       "legendFormat": "{{grpc_client_method}}"
      }
     ]
    },
    {
     "title": "estimated network overhead p99",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 171 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, operation) (rate(spicedb_grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"google.spanner.v1.Spanner/ExecuteStreamingSql\"}[$__rate_interval]))) - on () histogram_quantile(0.99, sum by(le, grpc_client_method) (rate(spicedb_cloud_google_com_go_spanner_gfe_latency_bucket{grpc_client_method=\"query\"}[$__rate_interval])))",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(spicedb_grpc_io_client_roundtrip_latency_bucket{grpc_client_method=\"google.spanner.v1.Spanner/ExecuteStreamingSql\"}[$__rate_interval]))) - on () histogram_quantile(0.99, sum by(le, grpc_client_method) (rate(spicedb_cloud_google_com_go_spanner_gfe_latency_bucket{grpc_client_method=\"query\"}[$__rate_interval])))",
       "legendFormat": "p95"
      }
     ]
    },
    {
     "title": "spanner RPC count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 179 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(grpc_client_method, grpc_client_status) (rate(spicedb_grpc_io_client_completed_rpcs[$__rate_interval]))",
       "legendFormat": "{{grpc_client_method}}/{{grpc_client_status}}"
      }
     ]
    },
    {
     "title": "Spanner num sessions available per client",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 179 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(pod, client_id) (spicedb_cloud_google_com_go_spanner_num_sessions_in_pool{type=\"num_sessions\"})",
       "legendFormat": "{{pod}}/{{client_id}}"
      }
     ]
    },
    {
     "title": "Spanner num sessions in use per client",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 179 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(pod, client_id) (spicedb_cloud_google_com_go_spanner_num_sessions_in_pool{type=\"num_in_use_sessions\"})",
       "legendFormat": "{{pod}}/{{client_id}}"
      }
     ]
    },
    {
     "title": "spanner received data per method",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 187 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, grpc_client_method) (rate(spicedb_grpc_io_client_received_bytes_per_rpc_bucket[$__rate_interval])))",
       "legendFormat": "{{grpc_client_method}}"
      }
     ]
    },
    {
     "title": "spanner sent data per method",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 187 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, grpc_client_method) (rate(spicedb_grpc_io_client_sent_bytes_per_rpc_bucket[$__rate_interval])))",
       "legendFormat": "{{grpc_client_method}}"
      }
     ]
    },
    {
     "title": "Spanner Get Session Timeouts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 187 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(spicedb_cloud_google_com_go_spanner_get_session_timeouts[$__rate_interval]))",
       "legendFormat": "timeouts"
      }
     ]
    }
   ]
  },
  {
   "title": "Schema Watch Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 },
   "collapsed": true,
   "panels": [
    {
     "title": "Schema Cache Hit-Ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 173 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(spicedb_datastore_watching_schema_cache_definitions_read_cached_total[$__rate_interval])) / sum(rate(spicedb_datastore_watching_schema_cache_definitions_read_total[$__rate_interval]))",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    },
    {
     "title": "Current Tracked Cache Revision",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 173 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(spicedb_datastore_watching_schema_cache_tracked_revision) / 1000000",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    },
    {
     "title": "Cache Fallback",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 173 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(spicedb_datastore_watching_schema_cache_namespaces_fallback_mode)",
       "legendFormat": "namespaces"
      },
      {
       "expr": "sum(spicedb_datastore_watching_schema_cache_caveats_fallback_mode)",
       "legendFormat": "caveats"
      }
     ]
    },
    {
     "title": "Schema Watch Cache Retries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 181 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(spicedb_datastore_spanner_schema_watch_retries_bucket[$__rate_interval])))",
       "legendFormat": "spanner"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(spicedb_datastore_crdb_schema_watch_retries_bucket[$__rate_interval])))",
       "legendFormat": "crdb"
      }
     ]
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 140 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Max RSS Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(process_resident_memory_bytes)",
     "legendFormat": "max across all pods"
    }
   ]
  },
  {
   "title": "Max/Avg Stack",
   "type": "timeseries",
   "description": "Max Stack usage across pods",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(go_memstats_stack_inuse_bytes)",
     "legendFormat": "in use max"
    },
    {
     "expr": "avg(go_memstats_stack_inuse_bytes)",
     "legendFormat": "in use avg"
    }
   ]
  },
  {
   "title": "Heap Stats (max)",
   "type": "timeseries",
   "description": "max heap usage across all pods",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(go_memory_classes_heap_free_bytes)",
     "legendFormat": "heap free"
    },
    {
     "expr": "max(go_memory_classes_heap_objects_bytes)",
     "legendFormat": "heap objects"
    },
    {
     "expr": "max(go_memory_classes_heap_released_bytes)",
     "legendFormat": "heap released"
    },
    {
     "expr": "max(go_memory_classes_heap_stacks_bytes)",
     "legendFormat": "heap stacks"
    },
    {
     "expr": "max(go_memory_classes_heap_unused_bytes)",
     "legendFormat": "heap unused"
    },
    {
     "expr": "max(go_memory_classes_os_stacks_bytes)",
     "legendFormat": "os stacks"
    },
    {
     "expr": "max(go_memory_classes_total_bytes)",
     "legendFormat": "total"
    },
    {
     "expr": "max(go_memory_classes_metadata_other_bytes)",
     "legendFormat": "metadata other"
    },
    {
     "expr": "max(go_memory_classes_other_bytes)",
     "legendFormat": "other"
    }
   ]
  },
  {
   "title": "Max Scanneable Heap Size",
   "type": "timeseries",
   "description": "The total amount of heap space that is scannable.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "max(go_gc_scan_heap_bytes)", "legendFormat": "max scanneable heap size" }
   ]
  },
  {
   "title": "GC CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "floor(sum(increase(go_cpu_classes_gc_total_cpu_seconds_total[$__rate_interval]))) / floor(sum(increase(go_cpu_classes_total_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "GC %"
    }
   ]
  },
  {
   "title": "GC Phases CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(go_cpu_classes_gc_mark_assist_cpu_seconds_total[$__rate_interval]))",
     "legendFormat": "Mark Assist"
    },
    {
     "expr": "sum(rate(go_cpu_classes_gc_mark_dedicated_cpu_seconds_total[$__rate_interval]))",
     "legendFormat": "Mark Dedicated"
    },
    {
     "expr": "sum(rate(go_cpu_classes_gc_pause_cpu_seconds_total[$__rate_interval]))",
     "legendFormat": "Pause"
    },
    {
     "expr": "sum(rate(go_cpu_classes_scavenge_assist_cpu_seconds_total[$__rate_interval]))",
     "legendFormat": "Scavenge Assist"
    },
    {
     "expr": "sum(rate(go_cpu_classes_scavenge_background_cpu_seconds_total[$__rate_interval]))",
     "legendFormat": "Scavenge Background"
    }
   ]
  },
  {
   "title": "GC time spent quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(quantile) (go_gc_duration_seconds)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "GC Cycles",
   "type": "timeseries",
   "description": "max heap usage across all pods",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "floor(sum(increase(go_gc_cycles_automatic_gc_cycles_total[$__rate_interval])))",
     "legendFormat": "automatic"
    },
    {
     "expr": "sum(increase(go_gc_cycles_forced_gc_cycles_total[$__rate_interval]))",
     "legendFormat": "forced"
    }
   ]
  },
  {
   "title": "GC Pauses",
   "type": "timeseries",
   "description": "max heap usage across all pods",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(go_gc_pauses_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(go_gc_pauses_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Object allocs / frees",
   "type": "timeseries",
   "description": "max heap usage across all pods",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 165 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(rate(go_gc_heap_allocs_objects_total[$__rate_interval]))",
     "legendFormat": "allocated objects"
    },
    {
     "expr": "max(rate(go_gc_heap_tiny_allocs_objects_total[$__rate_interval]))",
     "legendFormat": "allocated tiny objects"
    },
    {
     "expr": "max(rate(go_gc_heap_frees_objects_total[$__rate_interval]))",
     "legendFormat": "reclaimed objects"
    }
   ]
  },
  {
   "title": "Byte allocs / frees",
   "type": "timeseries",
   "description": "max heap usage across all pods",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 165 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(rate(go_gc_heap_frees_bytes_total[$__rate_interval]))",
     "legendFormat": "bytes reclaimed"
    },
    {
     "expr": "max(rate(go_gc_heap_allocs_bytes_total[$__rate_interval]))",
     "legendFormat": "bytes allocated"
    }
   ]
  },
  {
   "title": "target heap size of the next GC cycle",
   "type": "timeseries",
   "description": "shows the target heap size of the next GC cycle. GC’s goal is to keep go_memstats_heap_alloc_bytes less than this value",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 165 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_memstats_next_gc_bytes", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Total CPU Usage Across Fleet",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Per Process CPU Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "live goroutines per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "go_sched_goroutines_goroutines", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "avg goroutines over timeframe",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "avg by() (go_goroutines)", "legendFormat": "max" }
   ]
  },
  {
   "title": "max/avg goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "max(go_goroutines)", "legendFormat": "max" },
    { "expr": "avg(go_goroutines)", "legendFormat": "avg" }
   ]
  },
  {
   "title": "Go Scheduler Latency",
   "type": "timeseries",
   "description": "time it takes for a goroutine to be scheduled",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, operation) (rate(go_sched_latencies_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, operation) (rate(go_sched_latencies_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Per Process Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 189 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "process_open_fds", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "GOMAXPROCS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 189 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(go_sched_gomaxprocs_threads)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GOMEMLIMIT",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 189 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(go_gc_gomemlimit_bytes)", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "go version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 197 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max by(version) (go_info)", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Heap Allocations by size distribution",
   "type": "timeseries",
   "description": "Distribution of heap allocations by approximate size. Bucket counts increase monotonically. Note that this does not include tiny objects as defined by /gc/heap/tiny/allocs:objects, only tiny blocks.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 197 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(go_gc_heap_allocs_by_size_bytes_bucket[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(go_gc_heap_allocs_by_size_bytes_bucket[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Go Mutex Wait",
   "type": "timeseries",
   "description": "Approximate cumulative time goroutines have spent blocked on a sync.Mutex or sync.RWMutex. This metric is useful for identifying global changes in lock contention. Collect a mutex or block profile using the runtime/pprof package for more detailed contention data.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 197 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_sync_mutex_wait_total_seconds_total[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Go-to-C call rate",
   "type": "timeseries",
   "description": "Count of calls made from Go to C by the current process.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 205 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(go_cgo_go_to_c_calls_calls_total[$__rate_interval]))",
     "legendFormat": "call rate"
    }
   ]
  }
 ]
}