receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'prometheus'
          metrics_path: /api/v1alpha/metrics
          scrape_interval: 15s
          static_configs:
            - targets: ['app.admin.demo.aws.authzed.net']
          basic_auth:
            username: ${PROMETHEUS_USERNAME}
            password: ${PROMETHEUS_PASSWORD}

exporters:
  otlp:
    endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}
    headers:
      x-honeycomb-team: ${OTEL_EXPORTER_OTLP_HEADERS}

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [otlp]
