---
name: "Lint"
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
  pull_request:
    branches: ["*"]
jobs:
  lint:
    name: "Lint"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "authzed/actions/yaml-lint@main"
      - name: "Set up Kubeconform"
        uses: "bmuschko/setup-kubeconform@v1"
      - name: "Validate manifests"
        run: "kubeconform -summary -verbose ./kubernetes"
